name: dart_syntax_highlight
publish_to: none
environment:
  sdk: '>=2.14.0 <3.0.0'

dev_dependencies:
  collection: ^1.16.0
  json_schema2: ^2.0.3+5
  path: ^1.8.2
  string_scanner: ^1.1.1
  test: ^1.21.4
